org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
-Djava.net.preferIPv4Stack=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
systemProp.http.socketTimeout=180000
systemProp.http.connectionTimeout=180000
systemProp.https.socketTimeout=180000
systemProp.https.connectionTimeout=180000