package com.ruta.app.ui

import android.content.Intent
import android.os.Bundle
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.database.FirebaseDatabase
import com.ruta.app.R
import com.ruta.app.data.AuthRepository
import com.ruta.app.databinding.ActivitySignupBinding
import com.ruta.app.model.UserRole

class SignupActivity : AppCompatActivity() {

    private lateinit var binding: ActivitySignupBinding
    private val authRepository = AuthRepository()
    private lateinit var googleSignInClient: GoogleSignInClient

    // Register Activity Result Launcher for Google Sign-In
    private val googleSignInLauncher = registerForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
        try {
            val account = task.getResult(ApiException::class.java)
            account?.idToken?.let { idToken ->
                firebaseAuthWithGoogle(idToken, account.givenName, account.familyName)
            }
        } catch (e: ApiException) {
            showError("Google Sign-In failed: ${e.message}")
            setLoading(false)
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivitySignupBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Configure Google Sign-In
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id)) // Auto-generated by Firebase plugin
            .requestEmail()
            .build()
        googleSignInClient = GoogleSignIn.getClient(this, gso)

        binding.btnSignup.setOnClickListener { attemptSignup() }
        binding.btnGoogle.setOnClickListener { attemptGoogleSignup() }
        binding.btnFacebook.setOnClickListener { showError("Facebook sign in coming soon!") }

        binding.txtGoLogin.setOnClickListener {
            startActivity(Intent(this, LoginActivity::class.java))
            finish()
        }
    }

    private fun attemptSignup() {
        val firstName = binding.edtFirstName.text.toString().trim()
        val lastName = binding.edtLastName.text.toString().trim()
        val email = binding.edtEmail.text.toString().trim()
        val password = binding.edtPassword.text.toString()
        val confirmPassword = binding.edtConfirmPassword.text.toString()
        val role = selectedRole()

        if (firstName.isEmpty() || lastName.isEmpty()) {
            showError("Please enter both your first and last name.")
            return
        }

        if (password != confirmPassword) {
            showError("Passwords do not match.")
            return
        }

        setLoading(true)
        authRepository.signUp(firstName, lastName, email, password, role) { result ->
            setLoading(false)
            when (result) {
                is AuthRepository.Result.Success -> {
                    hideError()
                    goToLogin()
                }
                is AuthRepository.Result.Failure -> showError(result.message)
            }
        }
    }

    private fun attemptGoogleSignup() {
        setLoading(true)
        val signInIntent = googleSignInClient.signInIntent
        googleSignInLauncher.launch(signInIntent)
    }

    private fun firebaseAuthWithGoogle(idToken: String, firstName: String?, lastName: String?) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        val auth = FirebaseAuth.getInstance()

        auth.signInWithCredential(credential)
            .addOnSuccessListener { authResult ->
                val uid = authResult.user?.uid ?: ""
                val email = authResult.user?.email ?: ""
                val role = selectedRole()

                // Save user profile with Google profile first/last name
                val profile = mapOf(
                    "firstName" to (firstName ?: "Passenger"),
                    "lastName" to (lastName ?: ""),
                    "email" to email,
                    "role" to role.name
                )

                FirebaseDatabase.getInstance().getReference("users").child(uid).setValue(profile)
                    .addOnSuccessListener {
                        setLoading(false)
                        goToLogin()
                    }
            }
            .addOnFailureListener { e ->
                setLoading(false)
                showError("Firebase auth failed: ${e.message}")
            }
    }

    private fun selectedRole(): UserRole = when (binding.roleGroup.checkedRadioButtonId) {
        binding.roleDriver.id -> UserRole.DRIVER
        else -> UserRole.PASSENGER
    }

    private fun goToLogin() {
        startActivity(Intent(this, LoginActivity::class.java))
        finish()
    }

    private fun setLoading(loading: Boolean) {
        binding.btnSignup.isEnabled = !loading
        binding.btnGoogle.isEnabled = !loading
        binding.btnSignup.text = if (loading) "Processing..." else getString(R.string.signup_button)
    }

    private fun showError(message: String) {
        binding.txtError.text = message
        binding.txtError.visibility = android.view.View.VISIBLE
    }

    private fun hideError() {
        binding.txtError.visibility = android.view.View.GONE
    }
}